### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Qt_Oil_NewContent)
add_subdirectory(Qt_Oil_New)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Qt_Oil_NewContentplugin
    Qt_Oil_Newplugin)